name: Build .NET project

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Backend/EquiLog/EquiLog.sln

    - name: Build project
      run: dotnet build Backend/EquiLog/EquiLog.sln --no-restore

    - name: Show success message
      if: success()
      run: echo "✅ Build was successful!"

    - name: Show failure message
      if: failure()
      run: echo "❌ Something went wrong when building!"

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install frontend dependencies
      working-directory: Frontend/Equilog
      run: npm ci

    - name: Build frontend
      working-directory: Frontend/Equilog
      run: npm run build --if-present

    - name: Frontend build success message
      if: success()
      run: echo "✅ Angular frontend built successfully!"
